---
sdk: 
sdkversion: 4.0.0
name: angular
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.1
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.angular
  BundleURLScheme: angular
wp:
  productid: c0a453b0-d6b3-0130-e6d9-38f6b118e4ff
android:
  URIScheme: rho
  URIHost: com.rhomobile.angular
  package_name: "com.rhomobile.angular"
  version: 2.1
  android_title: 0
extensions:
- rhoconnect-client
minify_js: false
